### ISSUE TITLE
HELP: Unit test failing in Jenkins when building gradle-os-plugin

### ISSUE THREAD

**Issue by sc1478** [nebula-plugins/gradle-ospackage-plugin#176]
I am working on a revision to the gradle-os-package plugin.  When building on an ordinary linux server, the plugin builds without error, including all of my changes, which, in any case, only affect the RPM plugin.

When running the same build under Jenkins, the following tests fail, and I am trying to understand why.  The error messages don't help me much:
```

:testJava HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0


com.netflix.gradle.plugins.deb.DebPluginLauncherSpec > not up-to-date when specifying any value FAILED
    org.gradle.api.GradleException at DebPluginLauncherSpec.groovy:16
        Caused by: org.gradle.internal.exceptions.LocationAwareException
            Caused by: org.gradle.api.GradleScriptException
                Caused by: org.gradle.api.internal.plugins.PluginApplicationException
                    Caused by: org.gradle.api.plugins.PluginInstantiationException
                        Caused by: java.lang.NoClassDefFoundError
                            Caused by: java.lang.ClassNotFoundException

com.netflix.gradle.plugins.deb.DebPluginLauncherSpec > not up-to-date when specifying a value and not files FAILED
    org.gradle.api.GradleException at DebPluginLauncherSpec.groovy:31
        Caused by: org.gradle.internal.exceptions.LocationAwareException
            Caused by: org.gradle.api.GradleScriptException
                Caused by: org.gradle.api.internal.plugins.PluginApplicationException
                    Caused by: org.gradle.api.plugins.PluginInstantiationException
                        Caused by: java.lang.NoClassDefFoundError
                            Caused by: java.lang.ClassNotFoundException

com.netflix.gradle.plugins.deb.DebPluginLauncherSpec > not up-to-date when specifying a value on task FAILED
    org.gradle.api.GradleException at DebPluginLauncherSpec.groovy:48
        Caused by: org.gradle.internal.exceptions.LocationAwareException
            Caused by: org.gradle.api.GradleScriptException
                Caused by: org.gradle.api.internal.plugins.PluginApplicationException
                    Caused by: org.gradle.api.plugins.PluginInstantiationException
                        Caused by: java.lang.NoClassDefFoundError
                            Caused by: java.lang.ClassNotFoundException

com.netflix.gradle.plugins.deb.DebPluginLauncherSpec > not up-to-date when specifying a value on extension FAILED
    org.gradle.api.GradleException at DebPluginLauncherSpec.groovy:88
        Caused by: org.gradle.internal.exceptions.LocationAwareException
            Caused by: org.gradle.api.GradleScriptException
                Caused by: org.gradle.api.internal.plugins.PluginApplicationException
                    Caused by: org.gradle.api.plugins.PluginInstantiationException
                        Caused by: java.lang.NoClassDefFoundError
                            Caused by: java.lang.ClassNotFoundException

com.netflix.gradle.plugins.rpm.RpmPluginIntegrationTest > rpm task is marked up-to-date when setting arch or os property FAILED
    org.gradle.api.GradleException at RpmPluginIntegrationTest.groovy:22
        Caused by: org.gradle.internal.exceptions.LocationAwareException
            Caused by: org.gradle.api.GradleScriptException
                Caused by: java.lang.NoClassDefFoundError
                    Caused by: java.lang.ClassNotFoundException

com.netflix.gradle.plugins.packaging.SystemPackagingBasePluginTest > execute both tasks FAILED
    org.spockframework.runtime.SpockComparisonFailure at SystemPackagingBasePluginTest.groovy:108

136 tests completed, 6 failed, 3 skipped
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///var/lib/jenkins/workspace/gradle-ospackage-plugin/build/reports/tests/index.html
```

To get a little more detail, I see stack traces like the following, while looking the report linked above.  All of the failed test fail because of the same error:
```
not up-to-date when specifying any value

org.gradle.api.GradleException: Build aborted because of an internal error.
	at nebula.test.functional.internal.DefaultExecutionResult.rethrowFailure(DefaultExecutionResult.groovy:97)
	at nebula.test.IntegrationSpec.runTasksSuccessfully(IntegrationSpec.groovy:265)
	at com.netflix.gradle.plugins.deb.DebPluginLauncherSpec.not up-to-date when specifying any value(DebPluginLauncherSpec.groovy:16)
Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file '/var/lib/jenkins/workspace/gradle-os-package plugin/build/test/com.netflix.gradle.plugins.deb.DebPluginLauncherSpec/not-up-to-date-when-specifying-any-value/build.gradle' line: 2
A problem occurred evaluating root project 'not-up-to-date-when-specifying-any-value'.
...
Caused by: groovy.lang.MissingPropertyException: Could not find property 'com' on root project 'not-up-to-date-when-specifying-any-value'.
	at org.gradle.api.internal.AbstractDynamicObject.propertyMissingException(AbstractDynamicObject.java:43)
	at org.gradle.api.internal.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:35)
	at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:97)
	at org.gradle.groovy.scripts.BasicScript.propertyMissing(BasicScript.java:66)
	at build_47syfgngcdl39znslku94mawp.run(/var/lib/jenkins/workspace/gradle-os-package plugin/build/test/com.netflix.gradle.plugins.deb.DebPluginLauncherSpec/not-up-to-date-when-specifying-any-value/build.gradle:2)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 50 more


```

**Let me reiterate, on an ordinary Linux server, with the same code base, these errors do not occur.  Also, my only code change was on the rpm plugin, yet 5 of  these 6 errors are tests of the deb plugin which I've left utterly alone.**  Therefore I conclude that something is different in my jenkins environment than in my ordinary linux environment.  But what might that be?  I don't know enough about this test suite or about jenkins (newbie) to venture a guess.  The only clue I see is

Caused by: groovy.lang.MissingPropertyException: **Could not find property '_com_' on root project 'not-up-to-date-when-specifying-any-value'.**

**But I don't know what could be causing this, and I'm hoping someone here can give me a clue.**

Thanks.

**Comment by sc1478** [comment]
My non-forked version builds fine with Jenkins.  I should have tried that first.  Let me try to retrace my steps and see what I did wrong.  Still can't account for difference between running on plain linux server vs running on Jenkins though.  If these error message make sense to anyone, I'd still like an informed opinion, thanks.

**Comment by sc1478** [comment]
OK, please close this.  The same problem occurs without jenkins.  Last week it built and I can't see any changes.
