### ISSUE TITLE
Nullpointer at at org.freecompany.redline.Builder.checkVariableContainsIllegalChars

### ISSUE THREAD

**Issue by carlolf** [nebula-plugins/gradle-ospackage-plugin#190]
This is my first trial with the Rpm copy task. I chose a task which produced a tgz archive which worked great and I just changed the type of the task to  'type: Rpm'. I'm using Gradle 2.13 / 2.14 and 'gradle-ospackage-plugin:2.0.+'.
When the task is called it produces a curious nullpointer with this stack:
`
Caused by: java.lang.NullPointerException
        at org.freecompany.redline.Builder.checkVariableContainsIllegalChars(Builder.java:225)
        at org.freecompany.redline.Builder.setPackage(Builder.java:245)
        at com.netflix.gradle.plugins.rpm.RpmCopyAction.startVisit(RpmCopyAction.groovy:54)
        at com.netflix.gradle.plugins.packaging.AbstractPackagingCopyAction.execute(AbstractPackagingCopyAction.groovy:43)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator.execute(NormalizingCopyActionDecorator.java:52)
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator.execute(DuplicateHandlingCopyActionDecorator.java:42)
        at org.gradle.api.internal.file.copy.CopyActionExecuter.execute(CopyActionExecuter.java:38)
        at org.gradle.api.tasks.AbstractCopyTask.copy(AbstractCopyTask.java:83)
`

I'm wondering what this is?

**Comment by rspieldenner** [comment]
2.0.x is probably too old, go to the newest major.+

**Comment by carlolf** [comment]
ok, so I changed to '3.6.+'. Met the next cascade of exceptions, although the docs state there will be default values. So I declared these properties
`packageName = baseName
   version = project.version
   release = '3.3'
   arch = 'I386'
   os = 'LINUX'
   epoch = 1`
This helped me until the next NullpointerException, which I do not understand:
`Caused by: java.lang.NullPointerException
        at org.redline_rpm.header.Lead.write(Lead.java:92)
        at org.redline_rpm.Builder.build(Builder.java:1238)
        at com.netflix.gradle.plugins.rpm.RpmCopyAction.end(RpmCopyAction.groovy:173)
`

**Comment by carlolf** [comment]
Okay, further looking into the sources listed on the stacktrace, I have found that org.redline_rpm.header.Lead.write needs a type
`buffer.putShort(( short) type.ordinal());`
This is a  org.redline_rpm.header.RpmType. So in my case I declared `type = org.redline_rpm.header.RpmType.BINARY` in my script - and see, this worked! I have now a built rpm archive. If it is correct, well, this is another question.

Conclusion with my first experiences: the docs should give a valid example with all properties needed; not all defaults seem to exist. For my project, it was necessary to declare these properties:
`
   packageName = baseName
   version = project.version
   release = '3.3'
   arch = 'I386'
   os = 'LINUX'
   epoch = 1
   type = org.redline_rpm.header.RpmType.BINARY
   user = 'root'
   permissionGroup = 'root'
   vendor = 'myEmployer.xxx'
`

**Comment by carlolf** [comment]
Another thing I discoverd: the produced rpm file was locked after the build ended. I had to first stop the Gradle daemon before I could open the file.

**Comment by carlolf** [comment]
Is there anyone from https://code.google.com/archive/p/redline-rpm/issues listening here?

**Comment by sghill** [comment]
Some changes addressing the mentioned issues have happened recently:

#204 ensures the file is closed
#205 upgraded the version of redline to 1.2.4

> not all defaults seem to exist.

I'll take a look at this. Thanks!
