### ISSUE TITLE
java.lang.NoClassDefFoundError: com.google.common.base.Preconditions

### ISSUE THREAD

**Issue by tfiskgul** [nebula-plugins/gradle-ospackage-plugin#233]
Hello,

I was experimenting with the Nebula plugin:
```
buildscript {
	repositories {
		jcenter()
		mavenCentral()
		maven { url "http://repository.sonatype.org/content/groups/public/" }
	}

	dependencies {
		classpath 'com.netflix.nebula:gradle-ospackage-plugin:1.+'
	}
}

task fooDeb(type: Deb) {
	license 'MIT'
	release '1'
	requires 'somePackage'
}
```
And I got the following stacktrace; missing PreConditions from Guava?

```
* What went wrong:
A problem occurred evaluating project ':core'.
> com.google.common.base.Preconditions

Caused by: java.lang.NoClassDefFoundError: com.google.common.base.Preconditions
        at com.netflix.gradle.plugins.packaging.SystemPackagingExtension.class$(SystemPackagingExtension.groovy)
        at com.netflix.gradle.plugins.packaging.SystemPackagingExtension.$get$$class$com$google$common$base$Preconditions(SystemPackagingExtension.groovy)
        at com.netflix.gradle.plugins.packaging.SystemPackagingExtension.requires(SystemPackagingExtension.groovy:241)
        at com.netflix.gradle.plugins.packaging.SystemPackagingExtension.requires(SystemPackagingExtension.groovy:251)
        at com.netflix.gradle.plugins.packaging.SystemPackagingExtension$requires.call(Unknown Source)
        at com.netflix.gradle.plugins.packaging.SystemPackagingTask.requires(SystemPackagingTask.groovy)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:382)
        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:170)
        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:59)
        at build_f3rwa1pyicagxzrc6fvq26ixe$_run_closure5.doCall(/home/night/repos/fs/mux2fs/core/build.gradle:39)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:136)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:519)
        at org.gradle.api.internal.project.DefaultProject.task(DefaultProject.java:976)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:382)
        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:170)
        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:83)
        at build_f3rwa1pyicagxzrc6fvq26ixe.run(/home/night/repos/fs/mux2fs/core/build.gradle:36)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        ... 58 more


BUILD FAILED

Total time: 1.014 secs
```

Adding Guava to the classpath of the build script fixed the issue:
```
buildscript {
	repositories {
		jcenter()
		mavenCentral()
		maven { url "http://repository.sonatype.org/content/groups/public/" }
	}

	dependencies {
		classpath 'com.netflix.nebula:gradle-ospackage-plugin:1.+'
		classpath group: 'com.google.guava', name: 'guava', version: '21.+'
	}
}
```

But I think the nebula plugin should transitively mark that dependency itself?

**Comment by tfiskgul** [comment]
Sorry, I was using a wildly outdated version by mistake.
