### ISSUE TITLE
RPM 4.4.1 fails on Gradle 3.5.x

### ISSUE THREAD

**Issue by jschwanz** [nebula-plugins/gradle-ospackage-plugin#260]
Building an RPM with 4.4.0 works as expected with Gradle 3.5.x. Changing to 4.4.1 breaks with the following error:

```
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/tasks/WorkResults
        at com.netflix.gradle.plugins.packaging.AbstractPackagingCopyAction.execute(AbstractPackagingCopyAction.groovy:51)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator.execute(NormalizingCopyActionDecorator.java:53)
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator.execute(DuplicateHandlingCopyActionDecorator.java:42)
        at org.gradle.api.internal.file.copy.CopyActionExecuter.execute(CopyActionExecuter.java:40)
        at org.gradle.api.tasks.AbstractCopyTask.copy(AbstractCopyTask.java:179)
        at com.netflix.gradle.plugins.packaging.SystemPackagingTask.super$5$copy(SystemPackagingTask.groovy)
        at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure29.doCall(SystemPackagingTask.groovy:129)
        at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure29.doCall(SystemPackagingTask.groovy)
        at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:128)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:692)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:675)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
        ... 70 more
```

**Comment by DanielThomas** [comment]
@jschwanz I think I'm catching the wrong exception for that fallback, let me check and do a patch release if so.

**Comment by DanielThomas** [comment]
Fixed by https://github.com/nebula-plugins/gradle-ospackage-plugin/releases/tag/v4.4.2

**Comment by jschwanz** [comment]
@DanielThomas confirmed the fix resolved the issue, 1000 thumbs-up for the expeditious response
