### ISSUE TITLE
Error while building signed RPM

### ISSUE THREAD

**Issue by pvangool** [nebula-plugins/gradle-ospackage-plugin#270]
Hi,

I'm using gradle 3.5.1 and v4.4.0 of the ospackage plugin. While trying to build a signed RPM, I get the following error:

```
:buildRpm FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildRpm'.
> Error writing pending entry '268'.
```

I know my keyring is fine, and I know the passphrase is fine.

The stack trace shows:

```
Caused by: java.nio.BufferOverflowException
   at org.redline_rpm.header.AbstractHeader$BinEntry.write(AbstractHeader.java:677)
   at org.redline_rpm.header.AbstractHeader.writePending(AbstractHeader.java:201)
   ... 95 more
```

Is anybody else seeing this?

Thanks.

Paul

**Comment by pvangool** [comment]
I think I may be able to answer my own question. It has to do with the size of the key:

https://github.com/craigwblake/redline/issues/62
