### ISSUE TITLE
Could not expand ZIP - oracle jdk 10 - gradle 4.7

### ISSUE THREAD

**Issue by likewhatevs** [nebula-plugins/gradle-ospackage-plugin#289]
Could not expand ZIP - oracle jdk 10 - gradle 4.7
It looks like this may be the cause:
```
Caused by: java.lang.NullPointerException
        at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast(SystemUtils.java:1371)
        at org.apache.commons.lang3.SystemUtils$isJavaVersionAtLeast.call(Unknown Source)
        at com.netflix.gradle.plugins.deb.filevisitor.DebFileVisitorStrategyFactory.getStrategy(DebFileVisitorStrategyFactory.groovy:18)
```
I'll submit a MR if a version-bump of a dependency is all that is required (as I suspect it may be).

**Comment by rpalcolea** [comment]
This shouldn't be an issue anymore https://github.com/nebula-plugins/gradle-ospackage-plugin/commit/300349ab598ece152ea7e382c5323b3c168d2bef
