### ISSUE TITLE
Could not create buildDeb task

### ISSUE THREAD

**Issue by smandava-zpath** [nebula-plugins/gradle-ospackage-plugin#312]
After upgrading to latest 6.0.0 version of the plugin, gradle is failing to apply the plugin with the following error:

        ... 117 more
Caused by: org.gradle.api.InvalidUserDataException: You can't map a property that does not exist: propertyName=archiveFile
        at org.gradle.api.internal.ConventionAwareHelper.map(ConventionAwareHelper.java:56)
        at org.gradle.api.internal.ConventionAwareHelper.map(ConventionAwareHelper.java:80)
        at org.gradle.api.internal.ConventionMapping$map.call(Unknown Source)
        at com.netflix.gradle.plugins.packaging.SystemPackagingTask.applyConventions(SystemPackagingTask.groovy:109)
        at com.netflix.gradle.plugins.deb.Deb.super$7$applyConventions(Deb.groovy)
        at com.netflix.gradle.plugins.deb.Deb.applyConventions(Deb.groovy:51)
        at com.netflix.gradle.plugins.deb.DebPlugin$_apply_closure1.doCall(DebPlugin.groovy:37)
        at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)

**Comment by hndavis** [comment]
Have same issue.  It failis in tasktype = rpm

**Comment by chali** [comment]
Hi @smandava-zpath, could you provide an example of build file where you see this error?

**Comment by atorok** [comment]
In fact just 
```
plugins {
  id "nebula.ospackage" version "6.1.1"
}
```
and running `./gradlew` reproduces it. 
does hot reproduce with `5.2.0`

**Comment by atorok** [comment]
thanks for the update @chali I suspected something along those lines seeing that the property was present in Gradle master, but I was thrown off by the fact that the plugin has released versions whereas Gradle 5.1 is not yet released. 
I think it would be worth to add a check for the Gradle version when the plugin is applied, there are still many users of older Gradle versions who will be confused when copy/pasting from the Gradle plugin portal.

**Comment by stanimirivanovde** [comment]
I got the same error. The latest version of gradle is 5.0 and this will force us to use your older package version until 5.1 is released.

**Comment by AlphaDoraem** [comment]
> Ok, I looked into this and the reason is that `6.0.0` and higher are only compatible with Gradle 5.1+. Here are release notes https://github.com/nebula-plugins/gradle-ospackage-plugin/releases/tag/v6.0.0 We are going to move to Gradle 5.1 but there is a bunch of breaking changes in it so we are adopting plugins to it and releasing new major versions. If you are interested in `6.0.0` you

> Hi @smandava-zpath, could you provide an example of build file where you see this error?

hello,I have this question. My build.gradle:
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    System.properties['com.android.build.gradle.overrideVersionCheck'] = 'true'
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.1.0'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}//
When I build a project, it's wrong, "You can't map a property that does not exist: propertyName=dependencyCacheDir"
Could you help me?
