### ISSUE TITLE
ospackage plugin should support archive version

### ISSUE THREAD

**Issue by rpalcolea** [nebula-plugins/gradle-ospackage-plugin#361]
Gradle 6 introduced the following warnings:

```
ava.lang.IllegalArgumentException: Deprecation warnings were found (Set the ignoreDeprecations system property during the test to ignore):
 - The version property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveVersion property instead.
	at nebula.test.BaseIntegrationSpec.checkForDeprecations(BaseIntegrationSpec.groovy:96)
	at nebula.test.IntegrationSpec.checkForDeprecations(IntegrationSpec.groovy:169)
	at nebula.test.IntegrationSpec.runTasks(IntegrationSpec.groovy:164)
	at nebula.test.IntegrationSpec.runTasksSuccessfully(IntegrationSpec.groovy:147)
	at com.netflix.gradle.plugins.daemon.OspackageDaemonPluginLauncherSpec.override install cmd(OspackageDaemonPluginLauncherSpec.groovy:143)
``` 

We should modify the plugin to rely on `archiveVersion` instead.

It requires some work while applying conventions (https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/master/src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy#L74) and `SystemPackagingExtension` might need to be aware of this.

**Comment by gregallen** [comment]
I think this might be the cause of an issue I see whereby the buildRpm task will incorrectly decide it is UP-TO-DATE when the only thing changed is the version, e.g. set via a -P property, which should cause rpm to be rebuilt with a new name
