### ISSUE TITLE
Support for Gradle's configuration cache

### ISSUE THREAD

**Issue by birukoff** [nebula-plugins/gradle-ospackage-plugin#385]
If you enable Gradle's configuration cache, an attempt to build an RPM fails with message
```
5 problems were found storing the configuration cache, 1 of which seems unique.
- Task `:foo:bar` of type `com.netflix.gradle.plugins.rpm.Rpm`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/6.7/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
```
Please, add support for configuration cache.

**Comment by lockhartja** [comment]
Add to the problem

```
- task `:rpmArtifact` of type `com.netflix.gradle.plugins.rpm.Rpm`
    - [error] invocation of `Task.project` at execution time is unsupported with the configuration cache.
        - Exception at `com.netflix.gradle.plugins.packaging.SystemPackagingTask.getFakeFiles(SystemPackagingTask.groovy:391)`
org.gradle.api.InvalidUserCodeException: Invocation of 'Task.project' by task ':rpmArtifact' at execution time is unsupported with the configuration cache.
	at org.gradle.api.DefaultTask.getProject(DefaultTask.java:60)(28 internal lines hidden)
	at com.netflix.gradle.plugins.packaging.SystemPackagingTask.getFakeFiles(SystemPackagingTask.groovy:391)
	at com.netflix.gradle.plugins.rpm.Rpm_Decorated.getFakeFiles(Unknown Source)
	at org.gradle.internal.properties.bean.DefaultPropertyWalker$CachedPropertyValue.lambda$new$0(DefaultPropertyWalker.java:117)(9 internal lines hidden)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:198)
	at java.base/java.lang.Thread.run(Thread.java:840)(62 internal lines hidden)```

**Comment by wakingrufus** [comment]
Thanks for the report. I'll take a look at this
