### ISSUE TITLE
RPM task fails with StackOverflowError on Gradle 7.0 milestone 1

### ISSUE THREAD

**Issue by ericparton** [nebula-plugins/gradle-ospackage-plugin#393]
Hello,

I've been testing out my build with the pre-release version of Gradle 7.0, and the RPM task fails with a java.lang.StackOverflowError. Here's the stacktrace with more information:

        org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':project:rpm'.
                at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:187)
                at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:268)
                at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:185)
                at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
                at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
                at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
                at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
                at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
                at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
                at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
                at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
                at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
                at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
                at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
                at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
                at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
                at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
                at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
                at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
                at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
                at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:71)
                at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:408)
                at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:395)
                at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:388)
                at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:374)
                at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
                at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
                at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
                at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
                at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
                at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
                at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        Caused by: java.lang.StackOverflowError
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask.copy(SystemPackagingTask.groovy:167)
                at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy:168)
                at com.netflix.gradle.plugins.packaging.SystemPackagingTask$_copy_closure2.doCall(SystemPackagingTask.groovy)
                at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)

**Comment by breskeby** [comment]
We run into the same problem with the elasticsearch build. I'm wondering what a workaround would look like. Probably a quick fix could be do directly have the logic of super.copy() in this overrides copy function? I don't know if this is just a missbehaviour in groovy 3
